const PopulationConfig = {
    enabled: true,
    backgroundResolverEnabled: true,
    backgroundPartyEnabled: true,
    phasePolicyEnabled: true,
    directorEnabled: true,
    summaryIntervalMs: 30000,
    schedulerIntervalMs: 5000,
    partyFormationIntervalMs: 45000,
    phasePolicyIntervalMs: 10000,
    directorIntervalMs: 30000,
    maxResolvesPerTick: 10,
    partyFormationBatchSize: 3,
    partyFormationCandidateLimit: 80,
    partyMinSize: 2,
    partyMaxSize: 5,
    maxBackgroundParties: 20,
    cooldownGraceMs: 25000,
    cooldownBatchSize: 20,
    activationRadius: 6000,
    maxActivationsPerScan: 12,
    maxRestingActivationRatio: 0.35,
    activationRecoveryHpPct: 0.85,
    activationRecoveryMpPct: 0.85,
    activationPlacementRadius: 1400,
    activationMinPlayerDistance: 450,
    activationPlacementAttempts: 8,
    directorTargetBandRadius: 2,
    directorMaxCatchUpMultiplier: 1.35,
    directorSlowdownMultiplier: 0.85,
    eventLoopSampleMs: 1000,
    slowEventLoopLagMs: 75,
    debug: false
};

module.exports = PopulationConfig;
