'use strict';

const assert = require('node:assert/strict');
const Index = require('../src/GameServer/World/CharacterLocationIndex');
const Cache = require('../src/GameServer/Bot/Population/LifeStateCache');
const point = { locX: 0, locY: 0, locZ: 0 };
const values = [0, -0, NaN, Infinity, -Infinity, 42, 0n, 17n, '', 'state', false, true, Symbol('state')];
const index = new Index({ legacyStateCache: true }), strict = new Index();
const actor = { id: 1, source: {}, phase: 'hot', loc: point, spotId: 'one' };
const original = { id: 1, source: {}, phase: 'cold', loc: point, spotId: 'one' };
let reads = 0, tagReads = 0;
const rawObject = { id: 1, source: {}, phase: 'cold', get loc() { reads++; throw Error('raw object point'); } };
index.put(actor); index.setSource(1, 'state', original);
strict.setSource(1, 'state', rawObject, { indexed: false });
assert.equal(index.get(1), actor);
assert.equal(index.getSource(1, 'state'), original);
assert.deepEqual(index.near(point, 1), [actor]);
assert.deepEqual(index.nearSources(point, 1, { view: 'state', kind: 'cold' }), [original]);
assert.equal(strict.getSource(1, 'state'), rawObject);
assert.deepEqual([...strict.sourceValues('state')], [rawObject]);
assert.equal(reads, 0);
for (const value of [...values, null, undefined]) {
    const record = { id: 1, source: value, get phase() { tagReads++; return 'hot'; }, get loc() { reads++; return point; } };
    assert.throws(() => strict.setSource(1, 'state', record, { indexed: false }), RangeError);
    assert.throws(() => index.setSource(1, 'actor', record, { indexed: false }), RangeError);
    assert.throws(() => index.setSource(1, 'state', record, { indexed: true }), RangeError);
    assert.equal(strict.getSource(1, 'state'), rawObject);
    assert.equal(index.get(1), actor);
    assert.equal(index.getSource(1, 'state'), original);
    assert.equal(reads, 0, 'strict source validation runs before an otherwise valid point getter or eviction');
    assert.equal(tagReads, 0, 'strict source validation also precedes membership evaluation');
}
const cache = new Cache();
for (const [id, value] of values.entries()) {
    assert.equal(cache.set(id, value), cache);
    assert.equal(cache.has(id), true);
    assert(Object.is(cache.get(id), value));
}
cache.clear();
console.log('PASS actual strict/default/actor/indexed primitive rejection, raw object and successful Cache primitive positives');

const primitive = { id: 1, source: 0, get phase() { tagReads++; return 'hot'; }, spotId: 'one', get loc() { reads++; return point; } };
index.setSource(1, 'state', primitive, { indexed: false });
assert.equal(index.getSource(1, 'state'), primitive, 'successful Cache primitive must retain its ORIGINAL canonical raw record');
assert(Object.is(index.getSource(1, 'state').source, 0));
assert.equal(index.sourceSize('state'), 1);
assert.deepEqual([...index.sourceKeys('state')], [1]);
assert.deepEqual([...index.sourceValues('state')], [primitive]);
assert.equal(index.get(1), actor);
assert.deepEqual(index.nearSources(point, 1, { view: 'state' }), []);
assert.deepEqual(index.inSpotSources('one', { view: 'state' }), []);
assert.equal(reads, 0);
const actorCell = index.cells.get('0_0').actor.all, actorSpot = index.spots.get('one').actor;
const tagsBeforeEnable = tagReads;
assert.throws(() => index.updateSource(1, 'state', 0, { indexed: true }), RangeError);
assert.equal(reads, 0, 'enabling a raw primitive rejects before its valid point getter');
assert.equal(tagReads, tagsBeforeEnable, 'enabling a raw primitive rejects before membership evaluation');
assert.equal(index.getSource(1, 'state'), primitive);
assert.equal(index.cells.get('0_0').actor.all, actorCell);
assert.equal(index.spots.get('one').actor, actorSpot);
assert.equal(index.updateSource(1, 'state', 0), true);
assert.equal(index.updateSource(1, 'state', original.source), false);
assert.equal(index.removeSource(1, 'state', original.source), false);
for (const value of values) {
    const record = { id: 1, source: value, phase: 'hot', get loc() { reads++; return point; } };
    index.setSource(1, 'state', record, { indexed: false });
    assert.equal(index.getSource(1, 'state'), record);
    assert(Object.is(index.getSource(1, 'state').source, value));
    assert(Object.is(index.records.get(1).state.source, value));
    assert.equal(index.updateSource(1, 'state', value), true);
    assert.throws(() => index.updateSource(1, 'state', value, { indexed: true }), RangeError);
    assert.throws(() => index.setSource(1, 'state', record, { indexed: true }), RangeError);
    assert.equal(index.getSource(1, 'state'), record);
    assert.equal(reads, 0);
    assert.equal(index.removeSource(1, 'state', value), true);
    assert.equal(index.getSource(1, 'state'), null);
    assert.equal(index.sourceSize('state'), 0);
    assert.equal(index.get(1), actor);
}

const nan = { id: NaN, source: NaN, phase: 'hot' };
index.setSource(NaN, 'state', nan, { indexed: false });
assert.equal(index.updateSource(NaN, 'state', NaN), true);
assert.equal(index.getSource(NaN, 'state'), nan);
assert.equal(index.removeSource(NaN, 'state', NaN), true);
const positiveZero = { id: 0, source: 0, phase: 'hot' }, negativeZero = { id: -0, source: -0, phase: 'hot' };
index.setSource(0, 'state', positiveZero, { indexed: false });
const zeroEntry = index.records.get(0).state;
index.setSource(-0, 'state', negativeZero, { indexed: false });
assert.equal(index.records.get(0).state, zeroEntry);
assert(Object.is(index.getSource(0, 'state').source, -0));
assert(Object.is(zeroEntry.source, -0), 'canonical metadata retains the actual signed-zero source, not only its tuple equivalence');
assert.deepEqual([...index.sourceKeys('state')], [0]);
assert.equal(index.updateSource(0, 'state', 0), true, 'SameValueZero guard matches either zero sign');
assert.equal(index.removeSource(0, 'state', 0), true);
const symbol = Symbol('same'), otherSymbol = Symbol('same');
index.setSource(1, 'state', { id: 1, source: symbol, phase: 'hot' }, { indexed: false });
assert.equal(index.updateSource(1, 'state', otherSymbol), false);
assert.equal(index.removeSource(1, 'state', otherSymbol), false);
assert.equal(index.removeSource(1, 'state', symbol), true);
index.setSource(1, 'state', { id: 1, source: 0n, phase: 'hot' }, { indexed: false });
assert.equal(index.updateSource(1, 'state', 0), false);
assert.equal(index.removeSource(1, 'state', 0), false);
assert.equal(index.removeSource(1, 'state', 0n), true);

const opaque = {}, first = { id: opaque, source: false, phase: 'hot' }, second = { id: 'second', source: '', phase: 'hot' };
index.setSource(opaque, 'state', first, { indexed: false });
index.setSource('second', 'state', second, { indexed: false });
const live = index.sourceValues('state');
assert.equal(live.next().value, first);
const replacement = { id: 'second', source: NaN, phase: 'hot' };
index.setSource('second', 'state', replacement, { indexed: false });
assert.equal(second.source, '', 'a previously yielded/original wrapper is never mutated into its replacement');
const tail = { id: 'tail', source: 17n, phase: 'hot' };
index.setSource('tail', 'state', tail, { indexed: false });
assert.deepEqual([...index.sourceKeys('state')], [opaque, 'second', 'tail']);
assert.deepEqual([...live], [replacement, tail]);
assert.equal(index.removeSource('second', 'state', ''), false);
assert.equal(index.removeSource('second', 'state', NaN), true);
index.setSource('second', 'state', second, { indexed: false });
assert.deepEqual([...index.sourceKeys('state')], [opaque, 'tail', 'second']);
for (const source of [null, undefined]) {
    assert.throws(() => index.setSource(opaque, 'state', { id: opaque, source, phase: 'hot' }, { indexed: false }), RangeError);
    assert.equal(index.getSource(opaque, 'state'), first);
}
assert.throws(() => index.setSource(opaque, 'state', { ...first, phase: 'warm' }, { indexed: false }), RangeError);
assert.throws(() => index.setSource(opaque, 'state', { ...first, spotId: '' }, { indexed: false }), RangeError);
assert.equal(index.getSource(opaque, 'state'), first);
index.clearSourceView('state');
assert.equal(index.sourceSize('state'), 0);
assert.equal(index.get(1), actor);
assert.equal(index.cells.get('0_0').actor.all, actorCell);
assert.equal(index.spots.get('one').actor, actorSpot);
index.setSource(1, 'state', original);
assert.deepEqual(index.nearSources(point, 1, { view: 'state', kind: 'cold' }), [original]);
index.setSource(1, 'state', primitive, { indexed: false });
assert.deepEqual(index.nearSources(point, 1, { view: 'state' }), []);
index.setSource(1, 'state', original);
assert.deepEqual(index.inSpotSources('one', { view: 'state' }), [original]);
index.clearSourceView('actor');
assert.equal(index.getSource(1, 'state'), original);
assert.equal(index.get(1), null);
index.clear();
assert.equal(index.records.size, 0); assert.equal(index.cells.size, 0); assert.equal(index.spots.size, 0);
assert.equal(index.sourceSize('state'), 0); assert.equal(index.sourceSize('actor'), 0);
assert.equal(reads, 0);
console.log('PASS raw legacy primitives/default strict/prepoint guards/NaN/signed0/original values/live views/independent reset');
