const assert = require('assert');
const { PartyAdmission, priority } = require('../src/GameServer/Bot/Population/PartyAdmission');
const config = { maxBackgroundParties: 3 };
const parties = [{ stats: { capacityPool: 'social' } }, { stats: { objective: { priority: 'required' } } }];
const admission = new PartyAdmission();
const release = admission.reserve(parties, config);
assert(release);
assert.strictEqual(admission.reserve(parties, config), null, 'every producer shares in-flight reservations');
release(); release();
assert.strictEqual(admission.pending, 0);
assert.strictEqual(new PartyAdmission().reserve([...parties, {}], config), null, 'all persisted origins count after restart');
assert.strictEqual(admission.reserve([], { maxBackgroundParties: 0 }), null);
const at = 1800000000000;
const freshRequired = { status: 'open', priority: 'required', requestedAt: at };
const oldPreferred = { status: 'open', priority: 'preferred', requestedAt: at - 290000 };
assert(priority([oldPreferred], at) > priority([freshRequired], at), 'old voluntary requests can outrank newly urgent ones');
assert.strictEqual(priority([{ ...freshRequired, clanOperation: 'equipment' }], at), priority([freshRequired], at));
assert.strictEqual(priority([{ ...oldPreferred, status: 'deferred' }], at), 0);
assert.strictEqual(priority([{ status: 'open', priority: 'preferred' }], at), 0, 'missing request time is not infinite waiting');
require('../src/Global');
const Planner = invoke('GameServer/Bot/Population/PartyRequestPlanner');
const plan = { status: 'active', partyNeed: 'solo_ok', next: { spotId: 'test', npcId: 10 } };
const state = { activity: 'hunting', stats: { partyRequest: { ...oldPreferred, reason: 'shared_target', objectiveKey: 'route', spotId: 'test', npcId: 10 } } };
assert(Planner.partyRequestForPlan(state, plan, at), 'ordinary replans preserve current voluntary group intent');
assert.strictEqual(Planner.partyRequestForPlan(state, { ...plan, next: { spotId: 'other', npcId: 11 } }, at), null);
console.log('Unified party admission, aging and target-bound request checks passed');
