'use strict';
const assert = require('node:assert/strict');
const { create, LIMITS } = require('../src/GameServer/Bot/Economy/EconomyDiagnostics');
const off = create({ config: { developerDiagnostics: false, economyDiagnostics: true }, now() { throw Error('off clock'); } });
const payload = new Proxy({}, { get() { throw Error('off payload'); } });
assert.equal(off.push(payload), false); assert.equal(off.accept(payload), false);
assert.equal(off.connect(() => { throw Error('off transport'); }), false);
off.count(payload, payload, payload); off.duration(payload, payload);
assert.deepEqual(off.metrics(), { enabled: false }); assert.deepEqual(off.stats(), { enabled: false });
let clock = 100;
const config = { developerDiagnostics: true, economyDiagnostics: true, economyDiagnosticsBotIds: '64' };
const collector = create({ config, capacity: 1, now: () => clock, thread: 'worker' });
for (let i = 0; i < 100; i++) { collector.count('context', 'miss', String(i)); collector.duration('context', i); }
const metrics = collector.metrics();
assert.equal(Object.keys(metrics.counts).length, LIMITS.keys);
assert.equal(Object.values(metrics.counts).reduce((a, b) => a + b), 100, 'overflow preserves unsampled quantity');
assert.equal(metrics.durations.context.count, 100); assert.equal(metrics.durations.context.samples.length, LIMITS.durationSamples);
for (let i = 0; i < 40; i++) collector.duration('layer' + i, 1);
assert.equal(Object.keys(collector.metrics().durations).length, LIMITS.layers);
assert(collector.push({ owner: 64, commandId: 'first', sequence: 1, phase: 'native_purchase' }));
assert.equal(collector.push({ owner: 64, commandId: 'second', sequence: 2, phase: 'native_purchase' }), false);
assert.equal(collector.stats().drops.queue, 1);
const original = JSON.stringify({ owner: 64, at: 20, thread: 'worker', phase: 'purchase', commandId: 'first', sequence: 3 });
const forwarded = create({ config, now: () => clock }); const batches = [];
forwarded.connect(batch => { batches.push(batch); return true; });
assert.equal(forwarded.accept([original]), 1);
const event = JSON.parse(batches[0].records[0]);
assert.equal(event.at, 20); assert.equal(event.thread, 'worker'); assert.equal(event.sequence, 3);
assert.equal(forwarded.accept(new Array(17).fill(original)), false);
assert.equal(forwarded.ack(batches[0].id, 0), true); assert.equal(forwarded.stats().drops.writer, 1);
config.developerDiagnostics = false;
assert.deepEqual(collector.metrics(), { enabled: false }); assert.equal(collector.enabled(64), false);
collector.stop(); config.developerDiagnostics = true;
assert.equal(collector.stats().queued, 0); assert.deepEqual(collector.metrics().counts, {});
console.log('Developer diagnostics: master precedence, no off work, bounded unsampled aggregates/durations, drops, original time/thread and correlation passed');
