const assert = require('node:assert/strict');
const { BoardIndex, SELL } = require('../src/GameServer/AfkTrade/BoardIndex');
const BoardReviewEvents = require('../src/GameServer/Bot/Economy/BoardReviewEvents');
const board = new BoardIndex({ groupOf: () => 'material none' });
const queue = new BoardReviewEvents({ board });
const line = id => ({ lineId: id, selfId: 1864, count: 3, price: 20,
    pricing: { price: 20, seenCounter: 0, seenItem: 0, rival: 25, worth: 0, seenFills: 0 } });
for (let ownerId = 1; ownerId <= 300; ownerId++) board.put({ id: ownerId, ownerId,
    storeType: SELL, botOwned: true, lines: [line(ownerId)] });
assert.equal(queue.counterChanged, undefined, 'a deal has no owner fan-out entry point');
assert.equal(queue.resetCounterHistory, undefined);
assert.equal(queue.edgeOf, undefined);
assert.equal(queue.coverageVersion, undefined);
assert.deepEqual(queue.take(300), [], '300 priced owners are never queued by a counter');
board.ownersForCounter = () => { throw new Error('counter owner scan'); };
queue.ownerChanged(42);
queue.ownerChanged(42);
assert.deepEqual(queue.take(8), [42], 'only a named owner change enters the queue');
queue.rearm(42);
assert.deepEqual(queue.take(8), [], 'ack without a new own event does not spin');
queue.ownerChanged(42);
assert.deepEqual(queue.take(8), [42]);
queue.ownerChanged(42);
assert.deepEqual(queue.take(8), [], 'an in-flight owner keeps its token');
queue.deferAfterCommand(42);
assert.deepEqual(queue.take(8), [42], 'new own input in flight survives one ack');
queue.deferAfterCommand(42);
assert.deepEqual(queue.take(8), [], 'same rejected input cannot retry tightly');
queue.ownerChanged(42);
queue.defer(42);
assert.deepEqual(queue.take(8), []);
queue.ownerChanged(42);
assert.deepEqual(queue.take(8), [42], 'next named state change retries a deferred owner');
board.remove(42);
queue.ownerChanged(42);
queue.rearm(42);
assert.deepEqual(queue.take(8), [], 'line retirement drops its owner queue state');
queue.ownerChanged(43);
queue.clear();
queue.rearm(43);
assert.deepEqual(queue.take(8), [], 'restart clears every queue token');
assert.deepEqual(queue.take(0), []);
assert.deepEqual(queue.take(Infinity), []);
console.log('PASS named board owner queue, zero counter fan-out and bounded ack retries');
