const assert = require('node:assert/strict');
const fs = require('node:fs');
require('./helpers/databaseIsolation');
process.env.L2NODE_CONFIG_FILE = 'config/default.ini';
delete process.env.L2NODE_SHARED_CONFIG_FILE;
require('../src/Global');
const Population = invoke('GameServer/Bot/Population/PopulationService');
const { ColdSimulationCoordinator } = require('../src/GameServer/Bot/Population/ColdSimulationCoordinator');
const Shots = invoke('GameServer/Bot/Economy/ColdShotEconomyService');
const coordinator = new ColdSimulationCoordinator();
assert.equal(Population.reconcileShotEconomyBatch, undefined);
assert.equal(coordinator.withEconomyState, undefined);
assert.equal(coordinator.economyBots, undefined);
assert.equal(Shots.candidates, undefined);
const population = fs.readFileSync(require.resolve('../src/GameServer/Bot/Population/PopulationService'), 'utf8');
const source = fs.readFileSync(require.resolve('../src/GameServer/Bot/Population/ColdSimulationCoordinator'), 'utf8');
const shots = fs.readFileSync(require.resolve('../src/GameServer/Bot/Economy/ColdShotEconomyService'), 'utf8');
assert(!population.includes("'shot_economy'"));
assert(!source.includes('withEconomyState'));
assert(!source.includes('economy_in_progress'));
assert(!shots.includes('Workshops.inputSources'));
assert(!shots.includes('scanAt'));
assert(!shots.includes('SCAN_INTERVAL_MS'));
console.log('Cold economic handoff, periodic shot job and full holder scan are removed');
