'use strict';
const assert = require('node:assert/strict');
const Funding = require('../src/GameServer/Bot/Economy/PurchaseFunding');
const Config = require('../src/GameServer/Bot/Population/PopulationConfig');
const Diagnostics = require('../src/GameServer/Bot/Economy/EconomyDiagnostics');
const state = { characterId: 64, adena: 1000, stats: { money: [100, .001, 100, 0, .002, 200, 1], decisionSeq: 7, activityLeaf: 17, wishFocus: ['gear'] } };
Config.developerDiagnostics = false; Config.economyDiagnostics = true; Config.economyDiagnosticsBotIds = '64';
const first = Funding.spendable(state, 0, { r: .001, itemId: 1 });
assert.equal(first, 700); assert.deepEqual(Funding.summary(), { enabled: false });
Config.developerDiagnostics = true; const rows = [];
Diagnostics.connect(batch => { rows.push(...batch.records.map(JSON.parse)); return true; });
assert.equal(Funding.spendable(state, 0, { r: .001, itemId: 1 }), first);
const row = rows[0]; assert.equal(row.wallet, 1000); assert.equal(row.available, 700);
assert.equal(row.reserve, 100); assert.equal(row.priorityReserve, 200); assert.equal(row.decisionSeq, 7);
assert.equal(row.reason, 'funded_ratio'); assert.equal(row.wishKey, 'gear');
const saving = { ...state, stats: { ...state.stats, money: [100, .001, 100, 1000, .002, 200, 1] } };
assert.equal(Funding.spendable(saving, 0, { free: true }), 0);
assert.equal(Diagnostics.metrics().counts['funding:refused:funding_gap'], 1);
assert.equal(Funding.spendable(state, 0, { r: .0001, survivalCost: 30 }), 30);
Diagnostics.stop(); Config.developerDiagnostics = false;
console.log('Purchase funding diagnostics: original quantities, protected reserves, wallet versus available and refusal aggregates passed');
