const TRISKEL=7416, ARKENIA=7419, LEIKAN=7382, MOONSTONE_BEAST=369, CALPICO=5036;
const SHILENS_CALL=1245, ARKENIAS_LETTER=1246, LEIKANS_NOTE=1247, ONYX_BEASTS_MOLAR=1248, SHILENS_TEARS=1250, ARKENIA_RECOMMEND=1251, IRON_HEART=1252;
const ACCEPT="ItemSound.quest_accept", ITEM="ItemSound.quest_itemget", MIDDLE="ItemSound.quest_middle", FINISH="ItemSound.quest_finish";
const service=()=>invoke("GameServer/Quest/QuestService");
const page=(title,text,action="")=>`<html><body>${title}:<br>${text}<br><br>${action}</body></html>`;
const count=(state,id)=>state.session.actor.backpack.fetchItemFromSelfId(id)?.fetchAmount()||0;
module.exports={
  id:411,name:"Path to Assassin",npcs:[TRISKEL,ARKENIA,LEIKAN],startNpcs:[TRISKEL],killNpcs:[MOONSTONE_BEAST,CALPICO],
  eventNpc:(event)=>({start:TRISKEL,arkenia:ARKENIA,leikan:LEIKAN})[event]??null,
  async onEvent(state,event){const quest=service(),actor=state.session.actor;
    if(event==="start"&&!state.isStarted()&&!state.isCompleted()){if(Number(actor.fetchClassId())!==31||Number(actor.fetchLevel())<19||count(state,IRON_HEART))return null;await state.setState("started");await state.set("cond",1);await quest.giveItem(state.session,SHILENS_CALL,1);state.playSound(ACCEPT);return page("Triskel","Take Shilen's Call to Arkenia.");}
    if(event==="arkenia"&&count(state,SHILENS_CALL)){await quest.takeItem(state.session,SHILENS_CALL);await quest.giveItem(state.session,ARKENIAS_LETTER,1);await state.set("cond",2);state.playSound(MIDDLE);return page("Arkenia","Take my letter to Leikan.");}
    if(event==="leikan"&&count(state,ARKENIAS_LETTER)){await quest.takeItem(state.session,ARKENIAS_LETTER);await quest.giveItem(state.session,LEIKANS_NOTE,1);await state.set("cond",3);state.playSound(MIDDLE);return page("Leikan","Bring ten Moonstone Beast Molars.");}return null;},
  async onTalk(state,npc){const id=Number(npc.fetchSelfId()),quest=service();if(state.isCompleted())return page("Triskel","You have already completed the Path to Assassin.");if(!state.isStarted()){const a=state.session.actor;if(id!==TRISKEL||Number(a.fetchClassId())!==31)return page("Quest","This path is not for your current class.");return Number(a.fetchLevel())<19?page("Triskel","Come back after reaching level 19."):page("Triskel","Do you seek the path of an Assassin?",'<a action="bypass -h quest 411 start">Accept the trial.</a>');}
    if(id===TRISKEL){if(count(state,ARKENIA_RECOMMEND)){const result=await quest.awardFirstProfession(state,35);if(!result.ok)return page("Triskel","Your profession could not be granted. Keep the recommendation and try again.");await quest.takeItem(state.session,ARKENIA_RECOMMEND);await quest.giveItem(state.session,IRON_HEART,1);state.playSound(FINISH);await state.exit(false);return page("Triskel","You have completed the Path to Assassin and become an Assassin.");}return page("Triskel","Complete Arkenia's request.");}
    if(id===ARKENIA){if(count(state,SHILENS_CALL))return page("Arkenia","Triskel sent you?",'<a action="bypass -h quest 411 arkenia">Present Shilen’s Call.</a>');if(count(state,SHILENS_TEARS)){await quest.takeItem(state.session,SHILENS_TEARS);await quest.giveItem(state.session,ARKENIA_RECOMMEND,1);await state.set("cond",7);state.playSound(MIDDLE);return page("Arkenia","Take my recommendation to Triskel.");}return page("Arkenia","Continue Leikan's trial.");}
    if(id===LEIKAN){if(count(state,ARKENIAS_LETTER))return page("Leikan","Arkenia sent you?",'<a action="bypass -h quest 411 leikan">Accept Leikan’s request.</a>');if(count(state,LEIKANS_NOTE)&&count(state,ONYX_BEASTS_MOLAR)>=10){await quest.takeItem(state.session,ONYX_BEASTS_MOLAR,10);await quest.takeItem(state.session,LEIKANS_NOTE);await state.set("cond",5);state.playSound(MIDDLE);return page("Leikan","Now hunt Calpico for Shilen's Tears.");}if(count(state,LEIKANS_NOTE))return page("Leikan",`Moonstone Beast Molars: ${count(state,ONYX_BEASTS_MOLAR)}/10.`);return page("Leikan","Hunt Calpico for Shilen's Tears.");}
    return page("Quest","Continue your trial.");},
  async onKill(state,npc){if(!state.isStarted())return;const id=Number(npc.fetchSelfId()),quest=service();if(id===MOONSTONE_BEAST&&count(state,LEIKANS_NOTE)&&count(state,ONYX_BEASTS_MOLAR)<10){await quest.giveItem(state.session,ONYX_BEASTS_MOLAR,1);if(count(state,ONYX_BEASTS_MOLAR)===10){await state.set("cond",4);state.playSound(MIDDLE);}else state.playSound(ITEM);}else if(id===CALPICO&&!count(state,SHILENS_TEARS)){await quest.giveItem(state.session,SHILENS_TEARS,1);await state.set("cond",6);state.playSound(MIDDLE);}}
};
