const VARIKA=7421, CHARKEREN=7415, ANNIKA=7418, ARKENIA=7419;
const MARSH_ZOMBIE=15, KNEE_MOBS=[22,517,518], SKELETON_SCOUT=45;
const SEED_OF_ANGER=1253, SEED_OF_DESPAIR=1254, SEED_OF_HORROR=1255, SEED_OF_LUNACY=1256, FAMILYS_ASHES=1257, KNEE_BONE=1259, HEART_OF_LUNACY=1260, JEWEL_OF_DARKNESS=1261, LUCKY_KEY=1277, CANDLE=1278, HUB_SCENT=1279;
const ACCEPT="ItemSound.quest_accept",ITEM="ItemSound.quest_itemget",MIDDLE="ItemSound.quest_middle",FINISH="ItemSound.quest_finish";
const service=()=>invoke("GameServer/Quest/QuestService"),page=(t,x,a="")=>`<html><body>${t}:<br>${x}<br><br>${a}</body></html>`,count=(s,i)=>s.session.actor.backpack.fetchItemFromSelfId(i)?.fetchAmount()||0;
async function collect(s,id,n){if(count(s,id)>=n||Math.random()>=.5)return false;await service().giveItem(s.session,id,1);return count(s,id)>=n;}
module.exports={id:412,name:"Path to Dark Wizard",npcs:[VARIKA,CHARKEREN,ANNIKA,ARKENIA],startNpcs:[VARIKA],killNpcs:[MARSH_ZOMBIE,...KNEE_MOBS,SKELETON_SCOUT],eventNpc:e=>({start:VARIKA,anger:VARIKA,horror:VARIKA,lunacy:VARIKA,key:CHARKEREN,candle:ANNIKA})[e]??null,
async onEvent(s,e){const q=service(),a=s.session.actor;if(e==="start"&&!s.isStarted()&&!s.isCompleted()){if(Number(a.fetchClassId())!==38||Number(a.fetchLevel())<19||count(s,JEWEL_OF_DARKNESS))return null;await s.setState("started");await s.set("cond",1);await q.giveItem(s.session,SEED_OF_DESPAIR,1);s.playSound(ACCEPT);return page("Varika","Recover the three remaining Seeds.");}if(!s.isStarted())return null;if(e==="lunacy"&&!count(s,SEED_OF_LUNACY)&&!count(s,HUB_SCENT)){await q.giveItem(s.session,HUB_SCENT,1);return page("Varika","Collect three Hearts of Lunacy from Skeleton Scouts.");}if(e==="key"&&!count(s,SEED_OF_ANGER)&&!count(s,LUCKY_KEY)){await q.giveItem(s.session,LUCKY_KEY,1);return page("Charkeren","Collect three Family's Ashes from Marsh Zombies.");}if(e==="candle"&&!count(s,SEED_OF_HORROR)&&!count(s,CANDLE)){await q.giveItem(s.session,CANDLE,1);return page("Annika","Collect two Knee Bones from skeletons.");}return null;},
async onTalk(s,n){const id=Number(n.fetchSelfId()),q=service();if(s.isCompleted())return page("Varika","You have already completed the Path to Dark Wizard.");if(!s.isStarted()){const a=s.session.actor;if(id!==VARIKA||Number(a.fetchClassId())!==38)return page("Quest","This path is not for your current class.");return Number(a.fetchLevel())<19?page("Varika","Come back after reaching level 19."):page("Varika","Do you seek the path of a Dark Wizard?",'<a action="bypass -h quest 412 start">Accept the trial.</a>');}if(id===VARIKA){if([SEED_OF_DESPAIR,SEED_OF_ANGER,SEED_OF_HORROR,SEED_OF_LUNACY].every(x=>count(s,x))){const r=await q.awardFirstProfession(s,39);if(!r.ok)return page("Varika","Your profession could not be granted. Keep the Seeds and try again.");for(const x of [SEED_OF_DESPAIR,SEED_OF_ANGER,SEED_OF_HORROR,SEED_OF_LUNACY])await q.takeItem(s.session,x);await q.giveItem(s.session,JEWEL_OF_DARKNESS,1);s.playSound(FINISH);await s.exit(false);return page("Varika","You have completed the Path to Dark Wizard and become a Dark Wizard.");}const links=[];if(!count(s,SEED_OF_ANGER))links.push('<a action="bypass -h quest 412 anger">Seek the Seed of Anger.</a>');if(!count(s,SEED_OF_HORROR))links.push('<a action="bypass -h quest 412 horror">Seek the Seed of Horror.</a>');if(!count(s,SEED_OF_LUNACY))links.push('<a action="bypass -h quest 412 lunacy">Seek the Seed of Lunacy.</a>');return page("Varika","Choose a trial.",links.join("<br>"));}if(id===CHARKEREN){if(!count(s,LUCKY_KEY)&&!count(s,SEED_OF_ANGER))return page("Charkeren","Accept my request.",'<a action="bypass -h quest 412 key">Receive the Lucky Key.</a>');if(count(s,LUCKY_KEY)&&count(s,FAMILYS_ASHES)>=3){await q.takeItem(s.session,LUCKY_KEY);await q.takeItem(s.session,FAMILYS_ASHES,-1);await q.giveItem(s.session,SEED_OF_ANGER,1);s.playSound(MIDDLE);return page("Charkeren","Receive the Seed of Anger.");}return page("Charkeren",`Family's Ashes: ${count(s,FAMILYS_ASHES)}/3.`);}if(id===ANNIKA){if(!count(s,CANDLE)&&!count(s,SEED_OF_HORROR))return page("Annika","Accept my request.",'<a action="bypass -h quest 412 candle">Receive the Candle.</a>');if(count(s,CANDLE)&&count(s,KNEE_BONE)>=2){await q.takeItem(s.session,CANDLE);await q.takeItem(s.session,KNEE_BONE,-1);await q.giveItem(s.session,SEED_OF_HORROR,1);s.playSound(MIDDLE);return page("Annika","Receive the Seed of Horror.");}return page("Annika",`Knee Bones: ${count(s,KNEE_BONE)}/2.`);}if(id===ARKENIA){if(!count(s,HUB_SCENT)&&!count(s,SEED_OF_LUNACY)){await q.giveItem(s.session,HUB_SCENT,1);return page("Arkenia","Collect three Hearts of Lunacy.");}if(count(s,HUB_SCENT)&&count(s,HEART_OF_LUNACY)>=3){await q.takeItem(s.session,HUB_SCENT);await q.takeItem(s.session,HEART_OF_LUNACY,3);await q.giveItem(s.session,SEED_OF_LUNACY,1);s.playSound(MIDDLE);return page("Arkenia","Receive the Seed of Lunacy.");}return page("Arkenia",`Hearts of Lunacy: ${count(s,HEART_OF_LUNACY)}/3.`);}return page("Quest","Continue your trial.");},
async onKill(s,n){if(!s.isStarted())return;const id=Number(n.fetchSelfId());if(id===MARSH_ZOMBIE&&count(s,LUCKY_KEY)){if(await collect(s,FAMILYS_ASHES,3))s.playSound(MIDDLE);else if(count(s,FAMILYS_ASHES))s.playSound(ITEM);}else if(KNEE_MOBS.includes(id)&&count(s,CANDLE)){if(await collect(s,KNEE_BONE,2))s.playSound(MIDDLE);else if(count(s,KNEE_BONE))s.playSound(ITEM);}else if(id===SKELETON_SCOUT&&count(s,HUB_SCENT)){if(await collect(s,HEART_OF_LUNACY,3))s.playSound(MIDDLE);else if(count(s,HEART_OF_LUNACY))s.playSound(ITEM);}}
};
