const SIDRA=7330,TALBOT=7377,ADONIUS=7375,DARK_SUCCUBUS=776,ASHEN_BONE_MOBS=[457,458,514,515];
const SIDRAS_LETTER=1262,BLANK_SHEET=1263,BLOODY_RUNE=1264,GARMIEL_BOOK=1265,PRAYER_OF_ADON=1266,PENITENTS_MARK=1267,ASHEN_BONES=1268,ANDARIEL_BOOK=1269,ORB_OF_ABYSS=1270;
const ACCEPT="ItemSound.quest_accept",ITEM="ItemSound.quest_itemget",MIDDLE="ItemSound.quest_middle",FINISH="ItemSound.quest_finish";
const service=()=>invoke("GameServer/Quest/QuestService"),page=(t,x,a="")=>`<html><body>${t}:<br>${x}<br><br>${a}</body></html>`,count=(s,i)=>s.session.actor.backpack.fetchItemFromSelfId(i)?.fetchAmount()||0;
module.exports={id:413,name:"Path to Shillien Oracle",npcs:[SIDRA,TALBOT,ADONIUS],startNpcs:[SIDRA],killNpcs:[DARK_SUCCUBUS,...ASHEN_BONE_MOBS],eventNpc:e=>({start:SIDRA,sheets:TALBOT,mark:ADONIUS})[e]??null,
async onEvent(s,e){const q=service(),a=s.session.actor;if(e==="start"&&!s.isStarted()&&!s.isCompleted()){if(Number(a.fetchClassId())!==38||Number(a.fetchLevel())<19||count(s,ORB_OF_ABYSS))return null;await s.setState("started");await s.set("cond",1);await q.giveItem(s.session,SIDRAS_LETTER,1);s.playSound(ACCEPT);return page("Sidra","Take my letter to Talbot.");}if(e==="sheets"&&count(s,SIDRAS_LETTER)){await q.takeItem(s.session,SIDRAS_LETTER);await q.giveItem(s.session,BLANK_SHEET,5);await s.set("cond",2);s.playSound(MIDDLE);return page("Talbot","Collect five Bloody Runes from Dark Succubi.");}if(e==="mark"&&count(s,PRAYER_OF_ADON)){await q.takeItem(s.session,PRAYER_OF_ADON);await q.giveItem(s.session,PENITENTS_MARK,1);await s.set("cond",5);s.playSound(MIDDLE);return page("Adonius","Collect ten Ashen Bones.");}return null;},
async onTalk(s,n){const id=Number(n.fetchSelfId()),q=service();if(s.isCompleted())return page("Sidra","You have already completed the Path to Shillien Oracle.");if(!s.isStarted()){const a=s.session.actor;if(id!==SIDRA||Number(a.fetchClassId())!==38)return page("Quest","This path is not for your current class.");return Number(a.fetchLevel())<19?page("Sidra","Come back after reaching level 19."):page("Sidra","Do you seek the path of a Shillien Oracle?",'<a action="bypass -h quest 413 start">Accept the trial.</a>');}if(id===SIDRA){if(count(s,ANDARIEL_BOOK)&&count(s,GARMIEL_BOOK)){const r=await q.awardFirstProfession(s,42);if(!r.ok)return page("Sidra","Your profession could not be granted. Keep the books and try again.");await q.takeItem(s.session,ANDARIEL_BOOK);await q.takeItem(s.session,GARMIEL_BOOK);await q.giveItem(s.session,ORB_OF_ABYSS,1);s.playSound(FINISH);await s.exit(false);return page("Sidra","You have completed the Path to Shillien Oracle and become a Shillien Oracle.");}return page("Sidra","Complete Talbot and Adonius's trials.");}if(id===TALBOT){if(count(s,SIDRAS_LETTER))return page("Talbot","Sidra sent you?",'<a action="bypass -h quest 413 sheets">Receive the blank sheets.</a>');if(count(s,BLANK_SHEET)>0)return page("Talbot",`Bloody Runes: ${count(s,BLOODY_RUNE)}/5.`);if(count(s,BLOODY_RUNE)>=5){await q.takeItem(s.session,BLOODY_RUNE,-1);await q.giveItem(s.session,GARMIEL_BOOK,1);await q.giveItem(s.session,PRAYER_OF_ADON,1);await s.set("cond",4);s.playSound(MIDDLE);return page("Talbot","Take the Prayer of Adonius to Adonius.");}return page("Talbot","Continue Adonius's trial.");}if(id===ADONIUS){if(count(s,PRAYER_OF_ADON))return page("Adonius","Present the prayer.",'<a action="bypass -h quest 413 mark">Receive the Penitent’s Mark.</a>');if(count(s,PENITENTS_MARK)&&count(s,ASHEN_BONES)>=10){await q.takeItem(s.session,PENITENTS_MARK);await q.takeItem(s.session,ASHEN_BONES,-1);await q.giveItem(s.session,ANDARIEL_BOOK,1);await s.set("cond",7);s.playSound(MIDDLE);return page("Adonius","Take Andariel's Book to Sidra.");}if(count(s,PENITENTS_MARK))return page("Adonius",`Ashen Bones: ${count(s,ASHEN_BONES)}/10.`);return page("Adonius","Continue Talbot's trial.");}return page("Quest","Continue your trial.");},
async onKill(s,n){if(!s.isStarted())return;const id=Number(n.fetchSelfId()),q=service();if(id===DARK_SUCCUBUS&&count(s,BLANK_SHEET)>0){await q.takeItem(s.session,BLANK_SHEET);await q.giveItem(s.session,BLOODY_RUNE,1);if(!count(s,BLANK_SHEET)){await s.set("cond",3);s.playSound(MIDDLE);}else s.playSound(ITEM);}else if(ASHEN_BONE_MOBS.includes(id)&&count(s,PENITENTS_MARK)&&count(s,ASHEN_BONES)<10){await q.giveItem(s.session,ASHEN_BONES,1);if(count(s,ASHEN_BONES)===10){await s.set("cond",6);s.playSound(MIDDLE);}else s.playSound(ITEM);}}
};
