const KARUKIA=7570,KASMAN=7501,GOBLIN_TOMB_RAIDER_LEADER=320,KURUKA_RATMAN_LEADER=5045,UMBAR_ORC=5054;
const GREEN_BLOOD=1578,GOBLIN_DWELLING_MAP=1579,KURUKA_RATMAN_TOOTH=1580,BETRAYER_UMBAR_REPORT=1589,HEAD_OF_BETRAYER=1591,MARK_OF_RAIDER=1592;
const UMBAR_LOC=[-16760,78268,-3480],ACCEPT="ItemSound.quest_accept",ITEM="ItemSound.quest_itemget",MIDDLE="ItemSound.quest_middle",FINISH="ItemSound.quest_finish";
const service=()=>invoke("GameServer/Quest/QuestService"),page=(t,x,a="")=>`<html><body>${t}:<br>${x}<br><br>${a}</body></html>`,count=(s,i)=>s.session.actor.backpack.fetchItemFromSelfId(i)?.fetchAmount()||0;
module.exports={id:414,name:"Path to Orc Raider",npcs:[KARUKIA,KASMAN],startNpcs:[KARUKIA],killNpcs:[GOBLIN_TOMB_RAIDER_LEADER,KURUKA_RATMAN_LEADER,UMBAR_ORC],questSpawns:[KURUKA_RATMAN_LEADER],eventNpc:e=>(e==="start"?KARUKIA:null),
async onEvent(s,e){const q=service(),a=s.session.actor;if(e!=="start"||s.isStarted()||s.isCompleted())return null;if(Number(a.fetchClassId())!==44||Number(a.fetchLevel())<19||count(s,MARK_OF_RAIDER))return null;await s.setState("started");await s.set("cond",1);await q.giveItem(s.session,GOBLIN_DWELLING_MAP,1);s.playSound(ACCEPT);return page("Karukia","Bring ten Kuruka Ratman Teeth.");},
async onTalk(s,n){const id=Number(n.fetchSelfId()),q=service();if(s.isCompleted())return page("Karukia","You have already completed the Path to Orc Raider.");if(!s.isStarted()){const a=s.session.actor;if(id!==KARUKIA||Number(a.fetchClassId())!==44)return page("Quest","This path is not for your current class.");return Number(a.fetchLevel())<19?page("Karukia","Come back after reaching level 19."):page("Karukia","Do you seek the path of an Orc Raider?",'<a action="bypass -h quest 414 start">Accept the trial.</a>');}if(id===KARUKIA){if(count(s,GOBLIN_DWELLING_MAP)&&count(s,KURUKA_RATMAN_TOOTH)>=10){await q.takeItem(s.session,GOBLIN_DWELLING_MAP);await q.takeItem(s.session,KURUKA_RATMAN_TOOTH,-1);await q.giveItem(s.session,BETRAYER_UMBAR_REPORT,1);await s.addRadar(...UMBAR_LOC);await s.set("cond",3);s.playSound(MIDDLE);return page("Karukia","Find and punish the Umbar traitors.");}return page("Karukia",`Kuruka Ratman Teeth: ${count(s,KURUKA_RATMAN_TOOTH)}/10.`);}if(id===KASMAN&&count(s,BETRAYER_UMBAR_REPORT)&&count(s,HEAD_OF_BETRAYER)>=2){const r=await q.awardFirstProfession(s,45);if(!r.ok)return page("Kasman","Your profession could not be granted. Keep the heads and try again.");await q.takeItem(s.session,HEAD_OF_BETRAYER,-1);await q.takeItem(s.session,BETRAYER_UMBAR_REPORT);await s.removeRadar(...UMBAR_LOC);await q.giveItem(s.session,MARK_OF_RAIDER,1);s.playSound(FINISH);await s.exit(false);return page("Kasman","You have completed the Path to Orc Raider and become an Orc Raider.");}if(id===KASMAN)return page("Kasman",`Heads of Betrayers: ${count(s,HEAD_OF_BETRAYER)}/2.`);return page("Quest","Continue your trial.");},
async onKill(s,n){if(!s.isStarted())return;const id=Number(n.fetchSelfId()),q=service();if(id===GOBLIN_TOMB_RAIDER_LEADER&&count(s,GOBLIN_DWELLING_MAP)&&count(s,KURUKA_RATMAN_TOOTH)<10&&count(s,GREEN_BLOOD)<40){const blood=count(s,GREEN_BLOOD);if(blood>20&&Math.random()<((blood-20)*.05)){await q.takeItem(s.session,GREEN_BLOOD,-1);s.addSpawn(KURUKA_RATMAN_LEADER);}else{await q.giveItem(s.session,GREEN_BLOOD,1);s.playSound(ITEM);}}else if(id===KURUKA_RATMAN_LEADER&&count(s,GOBLIN_DWELLING_MAP)&&count(s,KURUKA_RATMAN_TOOTH)<10){await q.takeItem(s.session,GREEN_BLOOD,-1);await q.giveItem(s.session,KURUKA_RATMAN_TOOTH,1);if(count(s,KURUKA_RATMAN_TOOTH)===10){await s.set("cond",2);s.playSound(MIDDLE);}else s.playSound(ITEM);}else if(id===UMBAR_ORC&&count(s,BETRAYER_UMBAR_REPORT)&&count(s,HEAD_OF_BETRAYER)<2){await q.giveItem(s.session,HEAD_OF_BETRAYER,1);if(count(s,HEAD_OF_BETRAYER)===2){await s.set("cond",4);s.playSound(MIDDLE);}else s.playSound(ITEM);}}
};
