const GANTAKI=7587,ROSHEEK=7590,KASMAN=7501,TORUKU=7591;
const BEAR=479,SPIDER=478,SALAMANDER=415,FINAL_MOBS=new Map([[17,1609],[359,1610],[24,1611],[14,1612]]);
const POMEGRANATE=1593,P1=1594,P2=1595,P3=1596,P1F=1597,P2F=1598,P3F=1599,BEAR_CLAW=1600,SPIDER_TALON=1601,SALAMANDER_SCALE=1602,FIERY=1603,ROSHEEK_LETTER=1604,GANTAKI_LETTER=1605,FIG=1606,P4=1607,P4F=1608,IRON=1613,TORUKU_LETTER=1614,TOTEM=1615;
const ACCEPT="ItemSound.quest_accept",ITEM="ItemSound.quest_itemget",MIDDLE="ItemSound.quest_middle",FINISH="ItemSound.quest_finish";
const service=()=>invoke("GameServer/Quest/QuestService"),page=(t,x,a="")=>`<html><body>${t}:<br>${x}<br><br>${a}</body></html>`,count=(s,i)=>s.session.actor.backpack.fetchItemFromSelfId(i)?.fetchAmount()||0;
const finalTotal=s=>[1609,1610,1611,1612].reduce((n,i)=>n+count(s,i),0);
async function fill(s,pouch,full,trophy,need){const q=service();if(count(s,trophy)===need-1){await q.takeItem(s.session,trophy,-1);await q.takeItem(s.session,pouch);await q.giveItem(s.session,full,1);s.playSound(MIDDLE);return true;}await q.giveItem(s.session,trophy,1);s.playSound(ITEM);return false;}
module.exports={id:415,name:"Path to Monk",npcs:[GANTAKI,ROSHEEK,KASMAN,TORUKU],startNpcs:[GANTAKI],killNpcs:[BEAR,SPIDER,SALAMANDER,...FINAL_MOBS.keys()],eventNpc:e=>(e==="start"?GANTAKI:null),
async onEvent(s,e){const q=service(),a=s.session.actor;if(e!=="start"||s.isStarted()||s.isCompleted())return null;if(Number(a.fetchClassId())!==44||Number(a.fetchLevel())<19||count(s,TOTEM))return null;await s.setState("started");await s.set("cond",1);await q.giveItem(s.session,POMEGRANATE,1);s.playSound(ACCEPT);return page("Gantaki Zu Urutu","Take this Pomegranate to Rosheek.");},
async onTalk(s,n){const id=Number(n.fetchSelfId()),q=service();if(s.isCompleted())return page("Gantaki Zu Urutu","You have already completed the Path to Monk.");if(!s.isStarted()){const a=s.session.actor;if(id!==GANTAKI||Number(a.fetchClassId())!==44)return page("Quest","This path is not for your current class.");return Number(a.fetchLevel())<19?page("Gantaki Zu Urutu","Come back after reaching level 19."):page("Gantaki Zu Urutu","Do you seek the path of a Monk?",'<a action="bypass -h quest 415 start">Accept the trial.</a>');}
if(id===ROSHEEK){if(count(s,POMEGRANATE)){await q.takeItem(s.session,POMEGRANATE);await q.giveItem(s.session,P1,1);await s.set("cond",2);return page("Rosheek","Fill the first pouch with Kasha Bear Claws.");}if(count(s,P1F)){await q.takeItem(s.session,P1F);await q.giveItem(s.session,P2,1);await s.set("cond",4);return page("Rosheek","Fill the second pouch with Kasha Blade Spider Talons.");}if(count(s,P2F)){await q.takeItem(s.session,P2F);await q.giveItem(s.session,P3,1);await s.set("cond",6);return page("Rosheek","Fill the third pouch with Scarlet Salamander Scales.");}if(count(s,P3F)){await q.takeItem(s.session,P3F);await q.giveItem(s.session,FIERY,1);await q.giveItem(s.session,ROSHEEK_LETTER,1);await s.set("cond",8);return page("Rosheek","Return to Gantaki.");}return page("Rosheek","Continue filling your pouch.");}
if(id===GANTAKI){if(count(s,FIERY)&&count(s,ROSHEEK_LETTER)){await q.takeItem(s.session,ROSHEEK_LETTER);await q.giveItem(s.session,GANTAKI_LETTER,1);await s.set("cond",9);return page("Gantaki Zu Urutu","Take my letter to Kasman.");}return page("Gantaki Zu Urutu","Complete Rosheek's trials.");}
if(id===KASMAN){if(count(s,GANTAKI_LETTER)){await q.takeItem(s.session,GANTAKI_LETTER);await q.giveItem(s.session,FIG,1);await s.set("cond",10);return page("Kasman","Take this fig to Toruku.");}if(count(s,IRON)&&count(s,FIERY)&&count(s,TORUKU_LETTER)){const r=await q.awardFirstProfession(s,47);if(!r.ok)return page("Kasman","Your profession could not be granted. Keep the scrolls and try again.");for(const x of [IRON,FIERY,TORUKU_LETTER])await q.takeItem(s.session,x);await q.giveItem(s.session,TOTEM,1);s.playSound(FINISH);await s.exit(false);return page("Kasman","You have completed the Path to Monk and become a Monk.");}return page("Kasman","Complete Toruku's trial.");}
if(id===TORUKU){if(count(s,FIG)){await q.takeItem(s.session,FIG);await q.giveItem(s.session,P4,1);await s.set("cond",11);return page("Toruku","Fill the fourth pouch with the four kinds of trophies.");}if(count(s,P4F)){await q.takeItem(s.session,P4F);await q.giveItem(s.session,IRON,1);await q.giveItem(s.session,TORUKU_LETTER,1);await s.set("cond",13);return page("Toruku","Take my letter to Kasman.");}return page("Toruku",`Fourth pouch trophies: ${finalTotal(s)}/12.`);}return page("Quest","Continue your trial.");},
async onKill(s,n){if(!s.isStarted())return;const id=Number(n.fetchSelfId()),q=service();if(id===BEAR&&count(s,P1))await fill(s,P1,P1F,BEAR_CLAW,5);else if(id===SPIDER&&count(s,P2))await fill(s,P2,P2F,SPIDER_TALON,5);else if(id===SALAMANDER&&count(s,P3))await fill(s,P3,P3F,SALAMANDER_SCALE,5);else if(FINAL_MOBS.has(id)&&count(s,P4)){const trophy=FINAL_MOBS.get(id);if(count(s,trophy)>=3)return;if(finalTotal(s)>=11){for(const x of [1609,1610,1611,1612])await q.takeItem(s.session,x,-1);await q.takeItem(s.session,P4);await q.giveItem(s.session,P4F,1);s.playSound(MIDDLE);}else{await q.giveItem(s.session,trophy,1);s.playSound(ITEM);}}}
};
