const PIPPI=7524,MION=7519,SHARI=7517,BRONK=7525,ZIMENF=7538,TOMA=7556,RAUT=7316,TORAI=7557,HUNTER_BEAR=777,HONEY_BEAR=5058,HUNTER_TARANTULA=403,PLUNDER_TARANTULA=508;
const RING=1642,PIPPI_LETTER=1643,ROUT_SCROLL=1644,UNDIES=1645,MION_LETTER=1646,INGOT=1647,AXE=1648,POTION=1649,BRONK_PAY=1650,SHARI_PAY=1651,ZIMENF_PAY=1652,BEAR_PIC=1653,TARANTULA_PIC=1654,HONEY=1655,BEAD=1656,PARCEL=1657;
const ACCEPT="ItemSound.quest_accept",ITEM="ItemSound.quest_itemget",MIDDLE="ItemSound.quest_middle",FINISH="ItemSound.quest_finish";
const service=()=>invoke("GameServer/Quest/QuestService"),page=(t,x,a="")=>`<html><body>${t}:<br>${x}<br><br>${a}</body></html>`,count=(s,i)=>s.session.actor.backpack.fetchItemFromSelfId(i)?.fetchAmount()||0;
const jobs=[{item:INGOT,pay:BRONK_PAY,npc:BRONK,name:"Bronk"},{item:AXE,pay:SHARI_PAY,npc:SHARI,name:"Shari"},{item:POTION,pay:ZIMENF_PAY,npc:ZIMENF,name:"Zimenf"}];
const currentJob=s=>jobs.find(j=>count(s,j.item)||count(s,j.pay));
async function assign(s){const j=jobs[Math.floor(Math.random()*jobs.length)];await service().giveItem(s.session,j.item,1);return j;}
module.exports={id:417,name:"Path to Scavenger",npcs:[PIPPI,MION,SHARI,BRONK,ZIMENF,TOMA,RAUT,TORAI],startNpcs:[PIPPI],killNpcs:[HUNTER_BEAR,HONEY_BEAR,HUNTER_TARANTULA,PLUNDER_TARANTULA],questSpawns:[HONEY_BEAR],eventNpc:e=>({start:PIPPI,mion:MION,raut:RAUT,torai:TORAI})[e]??null,
async onEvent(s,e){const q=service(),a=s.session.actor;if(e==="start"&&!s.isStarted()&&!s.isCompleted()){if(Number(a.fetchClassId())!==53||Number(a.fetchLevel())<19||count(s,RING))return null;await s.setState("started");await s.set("cond",1);await q.giveItem(s.session,PIPPI_LETTER,1);s.playSound(ACCEPT);return page("Pippi","Take my letter to Mion.");}if(e==="mion"&&count(s,PIPPI_LETTER)){await q.takeItem(s.session,PIPPI_LETTER);const j=await assign(s);await s.set("cond",2);return page("Mion",`Take this errand to ${j.name}.`);}if(e==="raut"&&count(s,PARCEL)){await q.takeItem(s.session,PARCEL);await q.giveItem(s.session,ROUT_SCROLL,1);await s.set("cond",10);return page("Raut","Take the teleport scroll to Torai.");}if(e==="torai"&&count(s,ROUT_SCROLL)){await q.takeItem(s.session,ROUT_SCROLL);await q.giveItem(s.session,UNDIES,1);await s.set("cond",11);return page("Torai","Take the Succubus Undies to Raut.");}return null;},
async onTalk(s,n){const id=Number(n.fetchSelfId()),q=service();if(s.isCompleted())return page("Pippi","You have already completed the Path to Scavenger.");if(!s.isStarted()){const a=s.session.actor;if(id!==PIPPI||Number(a.fetchClassId())!==53)return page("Quest","This path is not for your current class.");return Number(a.fetchLevel())<19?page("Pippi","Come back after reaching level 19."):page("Pippi","Do you seek the path of a Scavenger?",'<a action="bypass -h quest 417 start">Accept the trial.</a>');}if(id===MION){if(count(s,PIPPI_LETTER))return page("Mion","Pippi sent you?",'<a action="bypass -h quest 417 mion">Accept Mion’s errand.</a>');const j=currentJob(s);if(j&&count(s,j.item))return page("Mion",`Take the errand to ${j.name}.`);if(j&&count(s,j.pay)){await q.takeItem(s.session,j.pay);const done=s.getInt("mionJobs")+1;await s.set("mionJobs",done);if(done>=3){await q.giveItem(s.session,MION_LETTER,1);await s.set("cond",4);return page("Mion","Take my letter to Toma.");}const next=await assign(s);return page("Mion",`Another errand: visit ${next.name}.`);}return page("Mion","Complete an errand.");}const j=jobs.find(x=>x.npc===id);if(j&&count(s,j.item)){await q.takeItem(s.session,j.item);await q.giveItem(s.session,j.pay,1);return page(j.name,"Take this payment back to Mion.");}if(id===TOMA){if(count(s,MION_LETTER)){await q.takeItem(s.session,MION_LETTER);await q.giveItem(s.session,BEAR_PIC,1);await s.set("cond",5);return page("Toma","Spoil Honey Bears for five Honey Jars.");}if(count(s,BEAR_PIC)&&count(s,HONEY)>=5){await q.takeItem(s.session,BEAR_PIC);await q.takeItem(s.session,HONEY,-1);await q.giveItem(s.session,TARANTULA_PIC,1);await s.set("cond",7);return page("Toma","Spoil tarantulas for twenty Beads.");}if(count(s,TARANTULA_PIC)&&count(s,BEAD)>=20){await q.takeItem(s.session,TARANTULA_PIC);await q.takeItem(s.session,BEAD,-1);await q.giveItem(s.session,PARCEL,1);await s.set("cond",9);return page("Toma","Take the Bead Parcel to Raut.");}return page("Toma",count(s,BEAR_PIC)?`Honey Jars: ${count(s,HONEY)}/5.`:`Beads: ${count(s,BEAD)}/20.`);}if(id===RAUT&&count(s,UNDIES)){const r=await q.awardFirstProfession(s,54);if(!r.ok)return page("Raut","Your profession could not be granted. Keep the Undies and try again.");await q.takeItem(s.session,UNDIES);await q.giveItem(s.session,RING,1);s.playSound(FINISH);await s.exit(false);return page("Raut","You have completed the Path to Scavenger and become a Scavenger.");}if(id===RAUT&&count(s,PARCEL))return page("Raut","Present the Bead Parcel.",'<a action="bypass -h quest 417 raut">Receive the teleport scroll.</a>');if(id===TORAI&&count(s,ROUT_SCROLL))return page("Torai","Present the teleport scroll.",'<a action="bypass -h quest 417 torai">Receive the Succubus Undies.</a>');return page("Quest","Continue your trial.");},
async onKill(s,n){if(!s.isStarted())return;const id=Number(n.fetchSelfId()),q=service();if(id===HUNTER_BEAR&&count(s,BEAR_PIC)&&count(s,HONEY)<5){const attempts=s.getInt("bearSearch");if(attempts>20&&Math.random()<=((attempts-20)*.1)){await s.set("bearSearch",0);s.addSpawn(HONEY_BEAR);}else await s.set("bearSearch",attempts+1);}else if(id===HONEY_BEAR&&count(s,BEAR_PIC)&&n.isSpoil?.()){await q.giveItem(s.session,HONEY,1);s.playSound(count(s,HONEY)===5?MIDDLE:ITEM);}else if([HUNTER_TARANTULA,PLUNDER_TARANTULA].includes(id)&&count(s,TARANTULA_PIC)&&n.isSpoil?.()&&count(s,BEAD)<20){const chance=(id===HUNTER_TARANTULA)?0.5:0.6;if(Math.random()<chance){await q.giveItem(s.session,BEAD,1);s.playSound(count(s,BEAD)===20?MIDDLE:ITEM);}}}
};
