const SILVERA=7527,KLUTO=7317,PINTER=7298,RATMAN=389,BIG_RATMAN=390,VUKU=17;
const RING=1632,PASS1=1633,PASS2=1634,PASS_FINAL=1635,TOOTH=1636,BIG_TOOTH=1637,KLUTO_LETTER=1638,FOOTPRINT=1639,BOX1=1640,BOX2=1641;
const ACCEPT="ItemSound.quest_accept",ITEM="ItemSound.quest_itemget",MIDDLE="ItemSound.quest_middle",FINISH="ItemSound.quest_finish";
const service=()=>invoke("GameServer/Quest/QuestService"),page=(t,x,a="")=>`<html><body>${t}:<br>${x}<br><br>${a}</body></html>`,count=(s,i)=>s.session.actor.backpack.fetchItemFromSelfId(i)?.fetchAmount()||0;
module.exports={id:418,name:"Path to Artisan",npcs:[SILVERA,KLUTO,PINTER],startNpcs:[SILVERA],killNpcs:[RATMAN,BIG_RATMAN,VUKU],eventNpc:e=>({start:SILVERA,letter:KLUTO,footprint:PINTER,box:PINTER})[e]??null,
async onEvent(s,e){const q=service(),a=s.session.actor;if(e==="start"&&!s.isStarted()&&!s.isCompleted()){if(Number(a.fetchClassId())!==53||Number(a.fetchLevel())<19||count(s,PASS_FINAL))return null;await s.setState("started");await s.set("cond",1);await q.giveItem(s.session,RING,1);s.playSound(ACCEPT);return page("Silvera","Bring ten Boogle Ratman Teeth and two Leader Teeth.");}if(e==="letter"&&count(s,PASS1)&&!count(s,KLUTO_LETTER)){await q.giveItem(s.session,KLUTO_LETTER,1);await s.set("cond",4);return page("Kluto","Take my letter to Pinter.");}if(e==="footprint"&&count(s,KLUTO_LETTER)){await q.takeItem(s.session,KLUTO_LETTER);await q.giveItem(s.session,FOOTPRINT,1);await s.set("cond",5);return page("Pinter","Recover the Stolen Secret Box from Vuku Orc Fighters.");}if(e==="box"&&count(s,FOOTPRINT)&&count(s,BOX1)){await q.takeItem(s.session,FOOTPRINT);await q.takeItem(s.session,BOX1);await q.giveItem(s.session,BOX2,1);await q.giveItem(s.session,PASS2,1);await s.set("cond",7);return page("Pinter","Return to Kluto.");}return null;},
async onTalk(s,n){const id=Number(n.fetchSelfId()),q=service();if(s.isCompleted())return page("Silvera","You have already completed the Path to Artisan.");if(!s.isStarted()){const a=s.session.actor;if(id!==SILVERA||Number(a.fetchClassId())!==53)return page("Quest","This path is not for your current class.");return Number(a.fetchLevel())<19?page("Silvera","Come back after reaching level 19."):page("Silvera","Do you seek the path of an Artisan?",'<a action="bypass -h quest 418 start">Accept the trial.</a>');}if(id===SILVERA){if(count(s,RING)&&count(s,TOOTH)>=10&&count(s,BIG_TOOTH)>=2){for(const x of [RING,TOOTH,BIG_TOOTH])await q.takeItem(s.session,x,-1);await q.giveItem(s.session,PASS1,1);await s.set("cond",3);return page("Silvera","Take the first pass to Kluto.");}return page("Silvera",`Boogle Ratman Teeth: ${count(s,TOOTH)}/10; Leader Teeth: ${count(s,BIG_TOOTH)}/2.`);}if(id===KLUTO){if(count(s,PASS1)&&count(s,PASS2)&&count(s,BOX2)){const r=await q.awardFirstProfession(s,56);if(!r.ok)return page("Kluto","Your profession could not be granted. Keep the passes and try again.");for(const x of [PASS1,PASS2,BOX2])await q.takeItem(s.session,x);await q.giveItem(s.session,PASS_FINAL,1);s.playSound(FINISH);await s.exit(false);return page("Kluto","You have completed the Path to Artisan and become an Artisan.");}if(count(s,PASS1)&&!count(s,KLUTO_LETTER))return page("Kluto","Accept my task.",'<a action="bypass -h quest 418 letter">Receive Kluto’s Letter.</a>');return page("Kluto","Complete Pinter's task.");}if(id===PINTER){if(count(s,KLUTO_LETTER))return page("Pinter","Present Kluto's Letter.",'<a action="bypass -h quest 418 footprint">Receive the Footprint.</a>');if(count(s,FOOTPRINT)&&count(s,BOX1))return page("Pinter","Present the Stolen Secret Box.",'<a action="bypass -h quest 418 box">Receive the second pass.</a>');return page("Pinter","Recover the Stolen Secret Box from Vuku Orc Fighters.");}return page("Quest","Continue your trial.");},
async onKill(s,n){if(!s.isStarted())return;const id=Number(n.fetchSelfId()),q=service();if(id===RATMAN&&count(s,RING)&&count(s,TOOTH)<10&&Math.random()<.7){await q.giveItem(s.session,TOOTH,1);s.playSound(count(s,TOOTH)===10&&count(s,BIG_TOOTH)>=2?MIDDLE:ITEM);}else if(id===BIG_RATMAN&&count(s,RING)&&count(s,BIG_TOOTH)<2&&Math.random()<.5){await q.giveItem(s.session,BIG_TOOTH,1);s.playSound(count(s,BIG_TOOTH)===2&&count(s,TOOTH)>=10?MIDDLE:ITEM);}else if(id===VUKU&&count(s,FOOTPRINT)&&!count(s,BOX1)&&Math.random()<.2){await q.giveItem(s.session,BOX1,1);await s.set("cond",6);s.playSound(MIDDLE);}}
};
